<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'LBL_PUBLISHER' => 'Editeur',
	'LBL_LICENSE' => 'License',
	'LBL_PUBLISHED_ON' => 'Publié on',
	'LBL_INSTALL' => 'Installer',
	'LBL_UPGRADE' => 'Mettre à jour',
	'LBL_VERSION' => 'Version',
	'LBL_DECLINE' => 'Refuser',
	'LBL_ACCEPT_AND_INSTALL' => 'Accepter et installer',
	'LBL_OK' => 'OK',
	'LBL_EXTENSION_NOT_COMPATABLE' => 'L\'extension n\'est pas compatible',
	'LBL_INVALID_FILE' => 'Fichier invalide',
	'LBL_NO_LICENSE_PROVIDED' => 'Aucune license fournie',
	'LBL_INSTALLATION' => 'Installation',
	'LBL_FAILED' => 'Echec',
	'LBL_SUCCESSFULL' => 'succès',
	'LBL_INSTALLATION_LOG' => 'Log d\'installation ',
	'LBL_UPDATED_MODULE' => ' mis à jour correctement.',
	'LBL_UPDATING_MODULE' => 'Mise à jour du module',
    
        //Extension Store translations
        'LBL_VTIGER_EXTENSION_STORE' => 'Boutique d\'extensions Vtiger - Place de marché',
        'LBL_SEARCH_FOR_AN_EXTENSION'  => 'Chercher une extension..',
        'LBL_DOWNLOADS' => 'Téléchargement',
        'LBL_NO_EXTENSIONS_FOUND' => 'Aucune extension trouvée',
        'LBL_REGISTER_TO_MARKET_PLACE' => 'Créer un compte sur la place de marché',
        'LBL_MARKETPLACE_REGISTRATION' => 'Création du compte dans la place de marché',
        'LBL_MARKETPLACE_LOGIN' => 'Login',
        'LBL_NEW_TO_MARKETPLCAE' => 'Nouveau sur la place de marché ?',
        'LBL_CREATE_AN_ACCOUNT' => 'Créer un compte',
        'LBL_SETUP_CARD_DETAILS' => 'Détails de la carte',
        'LBL_SETUP_CARD' => 'Renseignement de la carte',
        'LBL_CARD_NUMBER' => 'Numéro de carte',
        'LBL_EXP_MONTH' => 'Mois expiration',
        'LBL_EXP_YEAR' => 'Année expiration',
        'LBL_CVC_CODE' => 'CVC Code',
        'LBL_RESET' => 'Remise à zéro',
        'LBL_EXTENSION_STORE' => 'Boutique d\'extensions',
        'LBL_INSTALLED' => 'Installé',
        'LBL_UPDATE_CARD_DETAILS' => 'Mettre à jour la carte ',
        'LBL_BY' => 'par',
        'LBL_RATINGS' => 'Evaluations',
        'LBL_DESCRIPTION' => 'Description',
        'LBL_AUTHOR_INFORMATION' => 'Information sur l\'auteur',
        'LBL_AUTHOR_NAME' => 'Nom de l\'auteur',
        'LBL_PHONE' => 'Téléphone',
        'LBL_EMAIL' => 'Email',
        'LBL_SCREEN_SHOTS' => 'Copies d\'écran',
        'LBL_CUSTOMER_RATINGS' => 'Evaluations Clients',
        'LBL_CUSTOMER_REVIEWS' => 'Avis Clients',
        'LBL_WRITE_A_REVIEW' => 'Ecrire un avis',
        'LBL_CUSTOMER_REVIEW' => 'Avis Client',
        'LBL_REVIEW' => 'Avis',
        'LBL_CUSTOMERS_REVIEWED' => 'Avis Clients',
        'LBL_SINGLE_CUSTOMER_REVIEWED' => 'Avis Client',
        'LBL_INSTALLATION_FAILED' => 'Echec de l\'Installation',
        'LBL_SUCCESSFULL_INSTALLATION' => 'Installation réussie',
        'LBL_INSTALL_FROM_ZIP' => 'Installer depuis un Zip',
        'LBL_MORE_DETAILS' => 'Plus d\'informations',
        'Install' => 'Installer',
        'Upgrade' => 'Mettre à jour',
        'LBL_RATE_IT' => 'Evaluez.',
        'LBL_UNINSTALL' => 'Désinstaller',
        'LBL_LAUNCH' => 'Lancer',
        'LBL_SIGN_UP_FOR_FREE' => 'Inscription gratuite',
        'LBL_EMAIL_ADDRESS' => 'Email',
        'LBL_FIRST_NAME' => 'Prénom',
        'LBL_LAST_NAME' => 'Nom',
        'LBL_COMPANY_NAME' => 'Société',
        'LBL_PASSWORD' => 'Mot de passe',
        'LBL_CONFIRM_PASSWORD' => 'Confirmer Mot de passe',
        'LBL_REGISTER' => 'Inscription',
        'LBL_EXTENSION_STORE_LOGIN' => 'Login',
        'LBL_REMEMBER_ME' => 'Se souvenir de moi',
        'LBL_TRY_IT' => 'Essayer',
        'LBL_TRIAL_INSTALLED' => 'Version d\'essai installé',
        'LBL_BUY' => 'Acheter ',
        'LBL_LOGIN_TO_MARKET_PLACE' => 'Connexion à la place de marché',
        'LBL_LOGIN' => 'Login',
        'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'Veuillez installer "extension loader"',
        'LBL_INSTALL_EXTENSION_LOADER' => 'Installer "Extension Loader"',
        'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'Pour continuer d\'utiliser la boutique d\'extension, Installer ',
        'LBL_DOWNLOAD' => 'Télécharger',
        'LBL_COMPATIABLE_EXTENSION' => ' et activer en tant que "zend_extension".',
        'LBL_MORE_DETAILS_ON_INSTALLATION' => 'Plus de détails sur l\'installation',
        'LBL_READ_HERE' => 'Lire ici',
        'LBL_REVIEWS' => 'Avis',
        'LBL_SIGNUP_FOR_MARKET_PLACE' => 'Inscription à la place de marché',
        'LBL_UNAUTHORIZED' => 'Non authorisé',
        'LBL_EXPIRY_DATE'  => 'Date d\'expiration',
    
        'firstname' => 'Prénom',
        'lastname' => 'Nom',
        'email' => 'Email',
        'company' => 'Société',
        'Phone' => 'Téléphone',
        'Website' => 'Site Web',
        'LBL_SECURITY_CODE' => 'Code de sécurité',
        'LBL_WHAT_IS_SECURITY_CODE' => 'Code de sécurité ?',
        'LBL_CARD_NUMBER_PLACEHOLDER' => '16 chiffres de votre carte',
        'LBL_SECURITY_CODE_HELP_CONTENT' => 'The CVV Number(Card Verification Value) on your credit/debit card is a 3 digit number on VISA®, MasterCard® etc.. branded credit/debit cards.',
	'LBL_LOGOUT'	 => 	'Déconnexion' ,
);
$jsLanguageStrings = array(
  'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION'  => 'Renseigner les informations de la carte pour installer cette extension',
  'JS_UPDATE_CARD_DETAILS' => 'Mettre à jour les informations de la carte',
  'JS_ON' => 'de',
  'JS_RATINGS' => 'Avis',
  'JS_INSTALLED' => 'Installé',
  'JS_TRIAL_INSTALLED' => 'Essai Installé',
  'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'Installer "extension loader" pour installer cette extension depuis le lien',
  'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => 'Se connecter sur la place de marché pour installer cette extension ',
  'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => 'Renseigner les informations de la carte pour installer cette extension',
  'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => 'Se connecter à la place de marché pour désinstaller l\'extension',
  'JS_CARD_DETAILS_UPDATED' => 'Details de la carte mis à jour!',
  'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_INSTALL_THIS_EXTENSION' => 'Etes-vous certain de vouloir installer cette extension ?',  
  'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT_FROM_EXTENSION'	 => 	'Êtes-vous sûr de vouloir vous déconnecter de l\'extension?' ,
);