<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
 
$languageStrings = array(
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'Editeur d\'agencement et de champs'    , 
	'LBL_CREATE_CUSTOM_FIELD'      => 'Création d\'un champ personnalisé'         , 
	'LBL_DETAILVIEW_LAYOUT'        => 'Affichage de l\'agencement'          , 
	'LBL_ARRANGE_RELATED_TABS'     => 'Déplacer les modules liés'        , 
	'LBL_ADD_CUSTOM_FIELD'         => 'Ajouter un champ personnalisé'            , 
	'LBL_ADD_CUSTOM_BLOCK'         => 'Ajouter un bloc personnalisé'            , 
	'LBL_SAVE_FIELD_SEQUENCE'      => 'Enregistrer agencement'         , 
	'LBL_BLOCK_NAME'               => 'Nom du bloc'                  , 
	'LBL_ADD_AFTER'                => 'Ajouter après'                   , 
	'LBL_ACTIONS'                  => 'Actions'                     , 
	'LBL_ALWAYS_SHOW'              => 'Toujours afficher'                 , 
	'LBL_INACTIVE_FIELDS'          => 'Champs inactifs'             , 
	'LBL_DELETE_CUSTOM_BLOCK'      => 'Supprimer bloc personnalisé'         , 
	'LBL_MANDATORY_FIELD'          => 'Champ obligatoire'             , 
	'LBL_ACTIVE'                   => 'Actif'                      , 
	'LBL_QUICK_CREATE'             => 'Création rapide'                , 
	'LBL_SUMMARY_FIELD'            => 'Vue résumé'                , 
	'LBL_MASS_EDIT'                => 'Edition en masse'                   , 
	'LBL_DEFAULT_VALUE'            => 'Valeur par défaut'               , 
	'LBL_SELECT_FIELD_TYPE'        => 'Choix du type de champ'           , 
	'LBL_LABEL_NAME'               => 'Libellé'                  , 
	'LBL_LENGTH'                   => 'Longueur'                      , 
	'LBL_DECIMALS'                 => 'Décimales'                    , 
	'LBL_ENTER_PICKLIST_VALUES'    => 'Saisir les valeurs de la liste de choix..'     , 
	'LBL_PICKLIST_VALUES'          => 'Valeurs de la liste de choix'             , 
	'LBL_REACTIVATE'               => 'Réactiver'                  , 
	'LBL_ARRANGE_RELATED_LIST'     => 'Déplacer les modules liés'        , 
	'LBL_SELECT_MODULE_TO_ADD'     => 'Choix d\'un module à ajouter'        , 
	'LBL_NO_RELATED_INFORMATION'   => 'Aucune information liée'      , 
	'LBL_RELATED_LIST_INFO'        => 'Glisser/déposer le module pour modifier l\'ordre ', 
	'LBL_REMOVE_INFO'              => 'Cliquer sur l\'icone "croix" pour retirer le module de la liste', 
	'LBL_ADD_MODULE_INFO'          => 'Choix du module depuis les modules retirés à rajouter à la liste', 
	'LBL_SELECT_MODULE'            => 'Choix Module..'             , 
	'LBL_DUPLICATES_EXIST'         => 'Nom du bloc existant'   , 
	'LBL_NON_ROLE_BASED_PICKLIST'  => 'Liste à choix non basée sur les rôles'     , 
	'LBL_DUPLICATE_FIELD_EXISTS'   => 'Nom du champ existant'      , 
	'LBL_WRONG_FIELD_TYPE'         => 'Type de champ incorrect'            , 
	'LBL_ROLE_BASED_PICKLIST'      => 'Liste à choix basée sur les rôles'         , 
	//Field Types
	'Text'						   => 'Texte',
	'Decimal'					   => 'Décimal',
	'Integer'					   => 'Entier',
	'Percent'					   => 'Pourcentage',
	'Currency'					   => 'Devise',
	'Date'						   => 'Date',
	'Email'						   => 'Email',
	'Phone'						   => 'Téléphone',
	'PickList'					   => 'Liste déroulante',
	'MultiSelectCombo'			   => 'Case à cocher multiple',
	'URL' 						   => 'URL',
	'Checkbox' 					   => 'Case à cocher',
	'TextArea' 					   => 'Zone de texte',
	'Skype'						   => 'Skype',
	'Time'						   => 'Heure',
	'Calendar'	 => 	'Calendrier' ,
	'LayoutEditor'	 => 	'Éditeur de mise en page' ,
	'LBL_CLICK_HERE_TO_EDIT'	 => 	'Cliquez ici pour éditer' ,	
	
	// 7.1
	'LBL_SHOW_INACTIVE_FIELDS' => 'Afficher les champs inactifs',
	'LBL_SHOW_HIDDEN_FIELDS' => 'Afficher les champs cachés',
	'LBL_KEY_FIELD_VIEW' => 'Voir le champ essentiel',
	'LBL_SELECT_HIDDEN_MODULE' => 'Sélectionnez le module caché',
	'LBL_MANY_MANY_TEXT' => 'Les relations Many-to-Many ne sont actuellement disponibles que pour %s et %s',
	'LBL_EDIT_FIELD' => 'Modifier les propriétés du champ : %s',
	'LBL_FIELD_COULD_NOT_BE_CREATED' => 'Le champ %s n\'a pas pu être créé',
	'SELECT_MODULE' => 'Sélectionnez le module',
	'LBL_RELATION_SHIPS' => 'Relations',
	'LBL_ADD_RELATIONSHIP' => 'Ajouter une relation',
	'LBL_RELATED_MODULE' => 'Module lié',
	'LBL_ADDING_RELATIONSHIP' => 'Ajout d\'une relation pour %s',
	'LBL_SELECTED_RELATED_MODULE' => 'Sélectionnez le module lié',
	'LBL_SELECTED_RELATION_TYPE' => 'Sélectionnez le type de relation',
	'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => 'Relations 1-1 & N-1',
	'ONE_MANY_RELATIONSHIP' => 'Relations 1-N & N-N',
	'1-1' => '1-1',
	'1-N' => '1-N',
	'N-1' => 'N-1',
	'N-N' => 'N-N',
	'LBL_FIELD_TYPES' => 'Type de champ',
	'LBL_BASIC_FIELDS' => 'Champs de base',
	'LBL_MANDATORY' => 'Champ obligatoire',
	'LBL_PROPERTIES' => 'Propriétés',
	'LBL_DRAG_UI_TYPE' => 'Champ glisser-déposer',
	'LBL_RELATION_FIELDS' => 'Champs de relation',
	'LBL_SELECT_BLOCK' => 'Sélectionnez un bloc',
	'LBL_RELATION_ADDED_SUCCESS' => 'Relation ajoutée avec succès',
	'FIELD_NAME_IN_PRIMARY_MODULE' => 'Champ de relation dans %s',
	'FIELD_NAME_IN_RELATED_MODULE' => 'Champ de relation dans %s',
	'TAB_IN_PRIMARY_MODULE' => 'Tableau/onglet dans %s',
	'TAB_IN_RELATED_MODULE' => 'Tableau/onglet dans %s',
	'LBL_DETAIL_VIEW' => 'Vue détaillée',
	'LBL_EXPANDED' => 'Développé',
	'LBL_COLLAPSED' => 'Replié',
	'LBL_FILED_IN_PRIMARY_HELP_TEXT' => 'Champ de référence du module %s',
	'LBL_TAB_IN_PRIMARY_HELP_TEXT' => 'Tableau/onglet du module %s',
	'LBL_FILED_IN_RELATED_HELP_TEXT' => 'Champ de référence du module %s',
	'LBL_TAB_IN_RELATED_HELP_TEXT' => 'Tableau/onglet du module %s',
	'LBL_NO_RELATION_TYPE' => 'Aucune relation de ce type n\'existe',
	'LBL_CREATE_ITEM_CUSTOM_FIELD' => 'Créer un élément de ligne \'Champ personnalisé\'',
	'LBL_MAP_PRODUCT_FIELD' => 'Associer à un champ Produits',
	'LBL_MAP_SERVICE_FIELD' => 'Associer à un champ Services',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD' => 'Activer pour associer à un champ Produits',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD' => 'Activer pour associer à un champ Services',
	'LBL_NO_RELATED_INFO' => 'Aucune relation n\'existe',
	'LBL_ADD_NEW_FIELD_HERE' => 'Ajouter un nouveau champ ici',
	'LBL_SAVE_LAYOUT' => 'Enregistrer la mise en page',
	'LBL_SHOW_FIELD' => 'Afficher le champ',
	'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => 'Activer/désactiver les propriétés du champ',
	'LBL_PROP_MANDATORY' => 'obligatoire',
	'LBL_DEFAULT_VALUE_NOT_SET' => 'Valeur par défaut non définie',
	'LBL_INFO' => 'Info',
	'LBL_PRODUCTFIELDDEFAULTVALUE' => ' (Produits)',
	'LBL_SERVICEFIELDDEFAULTVALUE' => ' (Services)',
	'LBL_SHOW_THIS_FIELD_IN' => 'Cliquez ici pour afficher ce champ dans la vue %s',
	'LBL_MAKE_THIS_FIELD' => 'Cliquez ici pour rendre ce champ %s',
	'LBL_HIDE_THIS_FIELD_IN' => 'Cliquez ici pour masquer ce champ dans la vue %s',
	'LBL_NOT_MAKE_THIS_FIELD' => 'Cliquez ici pour que ce champ ne soit pas %s',
    'LBL_TAB_NAME_HELP_TEXT' => 'Liste de %s affichée dans l\'enregistrement %s',
    'LBL_TAB_NAME_TEXT' => 'Nom de l\'onglet de %s dans l\'enregistrement %s',
	'LBL_FILED_NAME_HELP_TEXT' => 'Un champ de référence à %s sera ajouté dans l\'enregistrement %s',
	'LBL_FIELD_NAME_TEXT' => 'Nom du champ de %s dans l\'enregistrement %s',
	'LBL_COLLAPSE_BLOCK' => 'Replier le bloc',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW' => 'Replier le bloc dans la vue détaillée',
	'LBL_HEADER' => 'Entête',
	'LBL_DETAIL_HEADER' => 'En-tête de l\'enregistrement',
	'LBL_HEADER_FIELD' => 'Vue entête',
	'LBL_DUPLICATE_HANDLING' => "Prévention des doublons",
	'LBL_DUPLICATE_CHECK' => "Activer la vérification des doublons",
	'LBL_DUPLICATION_INFO_MESSAGE' => "La fonction de prévention des doublons empêche uniquement la création de nouveaux enregistrements en double par les utilisateurs et les applications externes. Les enregistrements créés à partir d'imports et de flux de travail ne seront pas vérifiés pour les doublons.<br><br>Les doublons existants peuvent être supprimés à l'aide de la fonctionnalité \"Rechercher les doublons\" de la page du module.",
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => "Sélectionnez les champs uniques sur lesquels les enregistrements en double doivent être vérifiés",
	'LBL_SELECT_FIELDS' => "Sélectionnez les champs",
	'LBL_MAX_3_FIELDS' => "3 champs maximum",
	'LBL_SELECT_RULE' => "Sélectionnez la règle pour gérer les doublons",
	'LBL_ALLOW_DUPLICATES' => "Autoriser les doublons",
	'LBL_DO_NOT_ALLOW_DUPLICATES' => "Ne pas autoriser les doublons",
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => "Action à entreprendre si un enregistrement en double est détecté lors de la synchronisation avec une application externe",
	'LBL_PREFER_LATEST_RECORD' => "Préférer le dernier enregistrement",
	'LBL_PREFER_INTERNAL_RECORD' => "Préférer l'enregistrement interne",
	'LBL_PREFER_EXTERNAL_RECORD' => "Préférer l'enregistrement externe",
	'LBL_SYNC_TOOLTIP_MESSAGE' => "Préférer le dernier enregistrement - Les données modifiées le plus récemment, de l'enregistrement, seront conservées<br>Préférer l'enregistrement interne - L'enregistrement existant sera conservé tel quel<br>Préférer l'enregistrement externe - Les données de l'application externe seront copiées",
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW'     => 'Affichage du Bloc activé'          , 
	'JS_BLOCK_VISIBILITY_HIDE'     => 'Masquage du Bloc activé'          , 
	'JS_CUSTOM_BLOCK_ADDED'        => 'Nouveau bloc ajouté'      , 
	'JS_BLOCK_SEQUENCE_UPDATED'    => 'Séquence de Blocs mise à jour'     , 
	'JS_SELECTED_FIELDS_REACTIVATED' => ' sélectionnés réactivés' , 
	'JS_FIELD_DETAILS_SAVED'       => 'Details du champ enregistrés'         , 
	'JS_CUSTOM_BLOCK_DELETED'      => 'Bloc supprimé'        , 
	'JS_CUSTOM_FIELD_ADDED'        => 'Nouveau champ ajouté'      , 
	'JS_CUSTOM_FIELD_DELETED'      => 'Champ supprimé'        , 
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'Longueur doit être inférieur à', 
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Decimales entre 2 et 5', 
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Veuillez enregistrer les modifications d\'agencement', 
	'JS_RELATED_INFO_SAVED'        => 'Info relative enregistrée'          , 
	'JS_BLOCK_NAME_EXISTS'         => 'Nom du bloc existant'   , 
	'JS_NO_HIDDEN_FIELDS_EXISTS'   => 'Aucun champ inactif'          , 
	'JS_SPECIAL_CHARACTERS'        => 'les caractères spéciaux tel : '     , 
	'JS_NOT_ALLOWED'               => 'ne sont pas permis'             , 
	'JS_DUPLICATES_VALUES_FOUND'	 => 	'Des doublons ont été trouvés' ,
	'JS_FIELD_SEQUENCE_UPDATED'	 => 	'Agencement enregistré' ,
	
	// 7.1
	'JS_FIELD_IN_RELATED_MODULE' => 'Champ de relation dans %s',
	'JS_TAB_IN_RELATED_MODULE' => 'Tableau/onglet dans %s',
	'JS_FILED_IN_RELATED_HELP_TEXT' => 'Champ de référence du module %s',
	'JS_TAB_IN_RELATED_HELP_TEXT' => 'Tableau/onglet du module %s',
	'JS_TAB_FIELD_DELETION' => 'La suppression de la relation supprimera le champ %s dans le module %s et supprimera le tableau/onglet %s dans %s. Souhaitez-vous continuer ?',
	'JS_ONE_ONE_RELATION_FIELD_DELETE' => 'Cela supprimera le champ %s dans le module %s et supprimera le champ %s dans le module %s. Souhaitez-vous continuer ?',
	'JS_CUSTOM_FIELDS_MAX_LIMIT' => 'Vous ne pouvez ajouter qu\'un maximum de %s champs personnalisés dans le bloc %s',
	'JS_DEFAULT_VALUE_NOT_SET' => 'Valeur par défaut non définie',
	'JS_DEFAULT_VALUE' => 'Valeur par défaut',
	'JS_SAVE_MODULE_SEQUENCE' => 'Enregistrer les modifications pour mettre à jour la séquence du module associé',
	'JS_PRODUCTFIELDDEFAULTVALUE' => ' (Produits)',
	'JS_SERVICEFIELDDEFAULTVALUE' => ' (Services)',
	'JS_TAB_TAB_DELETION' => 'Cela supprimera l\'onglet %s dans le module %s et ses données. Souhaitez-vous continuer ?',
	'JS_SHOW_THIS_FIELD_IN' => 'Cliquez ici pour afficher ce champ dans la vue %s',
	'JS_MAKE_THIS_FIELD' => 'Cliquez ici pour rendre ce champ %s',
	'JS_HIDE_THIS_FIELD_IN' => 'Cliquez ici pour masquer ce champ dans la vue %s',
	'JS_NOT_MAKE_THIS_FIELD' => 'Cliquez ici pour que ce champ ne soit pas %s',
	'JS_TAB_NAME_HELP_TEXT' => 'Liste de %s affichée dans l\'enregistrement %s',
	'JS_TAB_NAME_TEXT' => 'Nom de l\'onglet de %s dans l\'enregistrement %s',
	'JS_FILED_NAME_HELP_TEXT' => 'Un champ de référence à %s sera ajouté dans l\'enregistrement %s',
	'JS_FIELD_NAME_TEXT' => 'Nom du champ de %s dans l\'enregistrement %s',
	'JS_PROP_MANDATORY' => 'obligatoire',
	'JS_SUMMARY' => 'Résumé',
	'JS_KEY_FIELD' => 'Champ essentiel',
	'JS_QUICK_CREATE' => 'Création rapide',
	'JS_MASS_EDIT' => 'Édition de masse',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Cette opération entraînera une suppression permanente des données.
                                                  Lorsqu\'un champ est supprimé, les valeurs stockées dans ce champ sont supprimées et ne peuvent pas être récupérées.
                                                  Si vous n\'êtes pas certain et que vous souhaitez pouvoir consulter ces données à l\'avenir, vous pouvez marquer le champ comme inactif au lieu de le supprimer. Les champs inactifs peuvent ensuite être réactivés à tout moment.
                                                  Êtes-vous sûr de vouloir supprimer ce champ ?',
	'JS_FIELD_DELETE_CONFIRMATION' => 'Supprimer - Je n\'ai pas besoin des données de ce champ.',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Le statut a été changé avec succès',
	'JS_FIELD_CAN_EITHER_BE_HEADER_OR_SUMMARY_ENABLED' => 'Le champ peut être soit un champ d\'en-tête ou un champ essentiel',
	'JS_DETAIL_HEADER' => 'Enregistrement d\'entête', // TODO: Review
	'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => 'Seul un maximum de %s champs d\'entête est autorisé',
	'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => 'Les noms des champs apparaissent par défaut dans l\'entête',
	'JS_FIELD_IS_HEADER_ENABLED_FOR_VTIGER7' => 'Ce champ est activé dans l\'entête pour vTiger7. Il apparaîtra dans la vue récapitulative',
	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => "Mise à jour des champs sélectionnés dans la prévention des doublons réussie ",
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => "Impossible de prendre en compte les champs sélectionnés dans la prévention des doublons",
	'JS_DUPLICATE_CHECK_DISABLED' => "La vérification des doublons est désactivée",
);
