<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.  
 ************************************************************************************/
$languageStrings = array(
	'MailConverter'                => 'Convertisseur de mail'              , 
	'MailConverter_Description'    => 'Scan de boîtes mail pour trouver des correspondances dans le CRM', 
	'MAILBOX'                      => 'Boîte mail'                     , 
	'RULE'                         => 'Règle'                        , 
	'LBL_ADD_RECORD'               => 'Ajouter boîte mail'                 , 
	'ALL'                          => 'Tout'                         , 
	'UNSEEN'                       => 'Non lu'                      , 
	'LBL_MARK_READ'                => 'Marque comme lu'                   , 
	'SEEN'                         => 'Lu'                        , 
	'LBL_EDIT_MAILBOX'             => 'Modifier boîte mail'                , 
	'LBL_CREATE_MAILBOX'           => 'Ajouter boîte mail'              , 
	'LBL_BACK_TO_MAILBOXES'        => 'Retour aux boîtes mail'           , 
	'LBL_MARK_MESSAGE_AS'          => 'Tagguer le message comme '             , 
	'LBL_MAX_LIMIT_ONLY_TWO'       => 'Vous pouvez configurer seulement 2 boîtes mail', 
	'LBL_IS_IN_RUNNING_STATE'      => 'est en cours de scan'         , 
	'LBL_SAVED_SUCCESSFULLY'       => 'Enregistré'          , 
	'LBL_CONNECTION_TO_MAILBOX_FAILED' => 'Echec de connexion à la boîte mail !', 
	'LBL_DELETED_SUCCESSFULLY'     => 'Supprimé'        , 
	'LBL_RULE_DELETION_FAILED'     => 'Echec de la suppression'        , 
	'LBL_RULES_SEQUENCE_INFO_IS_EMPTY' => 'information de règle manquante', 
	'LBL_SEQUENCE_UPDATED_SUCCESSFULLY' => 'Séquence mise à jour', 
	'LBL_SCANNED_SUCCESSFULLY'     => 'Scanné avec succès'        , 
	'scannername'                  => 'Nom du Convertisseur'                , 
	'server'                       => 'Nom du Serveur'                 , 
	'protocol'                     => 'Protocole'                    , 
	'username'                     => 'Nom d\'utilisateur'                   , 
	'password'                     => 'Mot de passe'                    , 
	'ssltype'                      => 'Type SSL'                    , 
	'sslmethod'                    => 'Méthode SSL'                  , 
	'connecturl'                   => 'URL de connexion'                 , 
	'searchfor'                    => 'Cherche pour'                    , 
	'markas'                       => 'Après le scan'                  , 
	'LBL_ENABLE'                   => 'Active'                      , 
	'LBL_DISABLE'                  => 'Inactive'                     , 
	'LBL_STATUS_MESSAGE'           => 'Vérifier pour rendre active'        , 
	'LBL_VALIDATE_SSL_CERTIFICATE' => 'Valider le certificat SSL '    , 
	'LBL_DO_NOT_VALIDATE_SSL_CERTIFICATE' => 'Ne pas valider le certificat SSL', 
	'LBL_ALL_MESSAGES_FROM_LAST_SCAN' => 'Tous les messages depuis le dernier scan' , 
	'LBL_UNREAD_MESSAGES_FROM_LAST_SCAN' => 'Les messages non lus depuis le dernier scan', 
	'LBL_MARK_MESSAGES_AS_READ'    => 'Tagguer les messages comme lus'       , 
	'LBL_I_DONT_KNOW'              => 'Je ne sais pas'               , 
	'LBL_SCAN_NOW'                 => 'Scanner maintenant'                    , 
	'LBL_RULES_LIST'               => 'listes des règles'                  , 
	'LBL_SELECT_FOLDERS'           => 'Choix des dossiers'              , 
	'LBL_SCANED_SUCCESSFULLY'      => 'Scanné avec succès'        , 
	'LBL_FOLDERS_INFO_IS_EMPTY'    => 'Information du dossier vide', 
	'LBL_UPDATE_FOLDERS'           => 'Mettre à jour les dossiers'              , 
	'fromaddress'                  => 'De'                        , 
	'toaddress'                    => 'Pour'                          , 
	'subject'                      => 'Sujet'                     , 
	'body'                         => 'Corps'                        , 
	'matchusing'                   => 'Correpond à'                       , 
	'action'                       => 'Action'                      , 
	'LBL_PRIORITY'                 => 'Priorité'                    , 
	'PRIORITISE_MESSAGE'           => 'Glisser/déposer les blocs pour déterminer l\'ordre d\'application des règles', 
	'LBL_ALL_CONDITIONS'           => 'Toutes les conditions'              , 
	'LBL_ANY_CONDITIOn'            => 'Au moins une condition'               , 
	'Contains'                     => 'Contient'                    , 
	'Not Contains'                 => 'Ne contient pas'                , 
	'Equals'                       => 'Egal à'                      , 
	'Not Equals'                   => 'Différent de'                  , 
	'Begins With'                  => 'Commence par'                       , 
	'Ends With'                    => 'Finit par'                         , 
	'Regex'                        => 'Regex'                       , 
	'CREATE_HelpDesk_FROM'         => 'Créer un Ticket (avec contact)'               , 
	'UPDATE_HelpDesk_SUBJECT'      => 'Mettre à jour Ticket (nouveau commentaire)'               , 
	'LINK_Contacts_FROM'           => 'Ajouter au Contact [De]'       , 
	'LINK_Contacts_TO'             => 'Ajouter au Contact [A]'         , 
	'LINK_Accounts_FROM'           => 'Ajouter au Compte [De]'  , 
	'LINK_Accounts_TO'             => 'Ajouter au Compte [A]'    , 
	'LINK_Leads_FROM'           => 'Ajouter au prospect [De]'  , 
	'LINK_Leads_TO'             => 'Ajouter au prospect [A]'    , 
	'LBL_UNSELECT_ALL'             => 'Tout déselectionner'                , 
	'LBL_CONVERT_EMAILS_TO_RESPECTIVE_RECORDS' => 'Convertir les emails vers les enregistrements respectifs', 
	'LBL_DRAG_AND_DROP_BLOCK_TO_PRIORITISE_THE_RULE' => 'Glisser/déposer les blocs pour déterminer l\'ordre d\'application des règles', 
	'LBL_ADD_RULE'                 => 'Ajouter Règle'                    , 
	'LBL_DELETE_RULE'              => 'Supprimer Règle'                 , 
	'LBL_BODY'                     => 'Corps'                        , 
	'LBL_MATCH'                    => 'Correspond'                       , 
	'LBL_ACTION'                   => 'Action'                      , 
	'LBL_FROM'                     => 'Expéditeur'                        , 
	'LBL_MAILCONVERTER_DESCRIPTION' => "Ce module permet de scanner une boîte mail et créer les actions appropriés dans votre CRM.<br />"
    . "Vous pourrez aussi définir des règles et y associer des actions spécifiques à la réception d'un email. <br />"
    . "Vos emails seront scannés automatiquement via le réglage dans le Planificateur. <br /><br /><br />",
    'LBL_CREATE_MAILBOX_NOW'       => 'Configurer une boîte mail à scanner'                        , 
    'LBL_ADDING_NEW_MAILBOX' => 'Ajout d\'une boîte mail',
    'MAILBOX_DETAILS'              => 'Réglages'                        , 
    'SELECT_FOLDERS'              => 'Choix des dossiers'                        , 
    'ADD_RULES'                     => 'Ajout de règles'                        , 
    'Scanner Name'                     => 'Libellé de la boîte mail'                        , 
    'Server'  => 'Serveur' , 
    'User Name'  => 'Nom d\'utilisateur' , 
    'Password'  => 'Mot de passe' , 
    'Protocol'  => 'Protocole' , 
    'SSL Type'  => 'Type SSL' , 
    'SSL Method'  => 'Méthode SSL' ,     
    'Look For'  => 'Action sur' , 
    'After Scan'  => 'Action après le traitement' , 
    'Time Zone'  => 'Fuseau horaire' , 
    'LBL_NEXT'  => 'Suivant' , 
    'TO_CHANGE_THE_FOLDER_SELECTION_DESELECT_ANY_OF_THE_SELECTED_FOLDERS' => 'Pour modifier la sélection des dossiers, sélectionner ou désélectionner les dossiers ci-dessous',
	'CREATE_Accounts_SUBJECT' => 'Créer un compte',
	'CREATE_Contacts_SUBJECT' => 'Créer un contact',
	'CREATE_Leads_SUBJECT' => 'Créer un prospect',
    'LBL_FINISH'  => 'Terminer' , 
	'LBL_CONDITIONS' => 'Conditions',       
    'LBL_RULE' => 'Règle',
    'LBL_MAILBOX' => 'boîte mail',
	'Connect URL'	 => 	'URL de connexion' ,
	'Do Not Validate SSL Certificate'	 => 	'Ne pas valider le certificat SSL' ,
	'LBL_ACTIONS'	 => 	'Actions' ,
	'LBL_CONNECTION_ERROR'	 => 	'Connexion à la boîte mail impossible. Vérifier votre connexion réseau et réessayez.' ,
	'LBL_FOLDERS_SCANNED'	 => 	'Dossiers scannés' ,
	'Status'	 => 	'Statut' ,
	'Validate SSL Certificate'	 => 	'Valider le certificat SSL' ,
	'LBL_MAX_LIMIT_EXCEEDED'	=> 'Vous avez dépassé la limite de boîtes mail supplémentaires !',
	
	// 7.1
	'isvalid' => 'Statut',
	'time_zone' => 'Fuseau horaire du serveur mail',
	'scanfrom' => 'Scanner les mails depuis',
	'YESTERDAY' => 'Hier',
	'LBL_NOTE' => 'Note',
	'LBL_MAILCONVERTER_DISABLE_MESSAGE' => 'Le convertisseur de mail sera supprimé le 31 juillet. Le \'Centre de mail\' offre un moyen plus simple de numériser vos courriels. Pour activer le \'Centre de mail\', veuillez ',
	'LBL_CLICK_HERE' => 'cliquer ici',
	'LBL_FROM_ADDRESS_PLACE_HOLDER' => 'Adresse email ou nom de domaine',
	'CREATE_HelpDeskNoContact_FROM' => 'Créer un ticket (sans contact)',
	'CREATE_Potentials_SUBJECT' => 'Créer une affaire (avec contact)',
	'CREATE_PotentialsNoContact_SUBJECT' => 'Créer une affaire (sans contact)',
	'LINK_Potentials_FROM' => 'Ajouter à l\'affaire [De]',
	'LINK_Potentials_TO' => 'Ajouter à l\'affaire [A]',
	'LINK_HelpDesk_FROM' => 'Ajouter au ticket [De]',
	'LINK_HelpDesk_TO' => 'Ajouter au ticket [A]',
	'LBL_EDIT_RULE' => 'Modifier règle',
	'LBL_RULE_CONDITIONS' => 'Conditions de la règle',
	'LBL_RULE_ACTIONS' => 'Actions de la règle',
	'LBL_AUTOFILL_VALUES_FROM_EMAIL_BODY' => 'Remplir automatiquement les valeurs à partir du corps du mail',
	'LBL_DELIMITER' => 'Séparateur',
	'LBL_COLON' => ': (Deux-points)',
    'LBL_SEMICOLON' => '; (Point-virgule)',
    'LBL_DASH' => '- (Trait d\'union)',
    'LBL_EQUAL' => '= (Egal)',
    'LBL_GREATER_THAN' => '> (Plus grand que)',
    'LBL_COLON_DASH' => ':- (Deux-points-Trait d\'union)',
    'LBL_COLON_EQUAL' => ':= (Deux-points-Egal)',
    'LBL_SEMICOLON_DASH' => ';- (Point-virgule-Point-virgule)',
    'LBL_SEMICOLON_EQUAL' => ';= (Point-virgule-Egal)',
    'LBL_EQUAL_GREATER_THAN' => '=> (Egal-Supérieur à)',
    'LBL_OTHER' => 'Autre',
    'LBL_DELIMITER_INFO' => 'Sélectionnez le délimiteur qui sépare les valeurs des étiquettes dans le corps de votre email',
    'LBL_EMAIL_BODY_INFO' => 'Copiez le texte d\'un exemple d\'email à numériser dans la case ci-dessous. vTiger tentera de localiser les valeurs et vous aidera à les mapper dans les champs du CRM.',
    'LBL_SAMPLE_BODY_TEXT' => 'Exemple de texte',
    'LBL_FIND_FIELDS' => 'Cliquez ici pour trouver les valeurs dans le corps du mail',
    'LBL_BODY_FIELDS' => 'Valeurs du mail',
    'LBL_CRM_FIELDS' => 'Champs du CRM',
    'LBL_MAP_TO_CRM_FIELDS' => 'Mapper les valeurs aux champs du CRM',
    'SELECT_FIELD' => 'Sélectionnez le champ',
    'LBL_SAVE_MAPPING_INFO' => 'Sauvegarder une règle de corps pour une règle existante du convertisseur de mail remplacera la règle de corps existante pour cette règle.',
    'LBL_MULTIPLE_FIELDS_MAPPED' => 'Impossible de mapper un champ CRM avec plusieurs champs',
    'LBL_BODY_RULE' => 'Règle du corps définie',
    'LBL_MAIL_SCANNER_INACTIVE' => 'Cette boîte mail est désactivée',
    'LBL_NO_RULES' => 'Aucune règle définie pour cette boîte mail',
    'LBL_SCANNERNAME_ALPHANUMERIC_ERROR' => 'Le nom du scanner accepte uniquement des caractères alphanumériques. Les caractères spéciaux ne sont pas autorisés.',
    'LBL_SERVER_NAME_ERROR' => 'Nom du serveur invalide. Les caractères spéciaux ne sont pas autorisés pour le nom du serveur.',
    'LBL_USERNAME_ERROR' => 'Entrez une adresse email valide pour le nom d\'utilisateur.',
    'servertype' => 'Type de serveur',
    'LBL_DUPLICATE_USERNAME_ERROR' => 'Il existe déjà un convertisseur de mail configuré avec cette adresse mail. Vous ne pouvez pas créer un convertisseur de mail en double avec la même adresse mail.',
    'LBL_DUPLICATE_SCANNERNAME_ERROR' => 'Il existe déjà un convertisseur de mail configuré avec ce nom. Vous ne pouvez pas créer un convertisseur de mail en double avec le même nom.',
);

$jsLanguageStrings = array(
	'JS_MAILBOX_DELETED_SUCCESSFULLY' => 'Boîte mail supprimée', 
	'JS_MAILBOX_LOADED_SUCCESSFULLY' => 'Boîte mail scannée' , 
	
	// 7.1
    'JS_SELECT_ATLEAST_ONE' => 'Veuillez mapper au moins un champ',
    'JS_SERVER_NAME' => 'Entrez le nom du serveur',
	'JS_TIMEZONE' => 'Fuseau horaire du serveur mail',
    'JS_SCAN_FROM' => 'Scanner des emails depuis',
    'JS_TIMEZONE_INFO' => 'Sélectionnez le fuseau horaire où se trouve votre serveur mail. La sélection d\'un mauvais fuseau horaire pourrait empêcher le scan de certains mails.',
    'JS_SCAN_FROM_INFO' => 'Ce champ définit si tous les mails dans votre boîte mail doivent être scannés ou si seulement les mails qui ont atterri dans votre boîte mail hier ou plus tard devraient être scannés. Ce champ est applicable uniquement pour la première configuration ou lorsque vous sélectionnez un nouveau dossier à scanner.',
    'JS_SELECT_ONE_FOLDER' => 'Vous devez sélectionner au moins un dossier.',
);
