<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved. 
 ************************************************************************************/
$languageStrings = array(
	'LBL_NEW'                      => 'Nouveau'                         , 
	'LBL_WORKFLOW'                 => 'Flux de travail'                    , 
	'LBL_CREATING_WORKFLOW'        => 'Nouveau flux de travail'           , 
	'LBL_NEXT'                     => 'Suivant'                        , 
	'LBL_STEP_1'                   => 'Etape 1'                      , 
	'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'Description du flux de travail', 
	'LBL_SPECIFY_WHEN_TO_EXECUTE'  => 'Préciser quand exécuter le flux de travail', 
	'ON_FIRST_SAVE'                => 'Seulement à la création'      , 
	'ONCE'                         => 'Une seule fois dès l\'instant où la condition est vraie', 
	'ON_EVERY_SAVE'                => 'A chaque fois que l\'enregistrement est sauvegardé', 
	'ON_MODIFY'                    => 'A chaque fois que l\'enregistrement est modifié', 
	'MANUAL'                       => 'Système'                      , 
	'SCHEDULE_WORKFLOW'            => 'Condition d\'éxecution'           , 
	'ADD_CONDITIONS'               => 'Ajouter Conditions'              , 
	'ADD_TASKS'                    => 'Ajouter Tâche'                   , 
	'LBL_EXPRESSION'               => 'Expression'                  , 
	'LBL_FIELD_NAME'               => 'Champ'                       , 
	'LBL_SET_VALUE'                => 'Définir valeur'                   , 
	'LBL_USE_FIELD'                => 'Utiliser champ'                   , 
	'LBL_USE_FUNCTION'             => 'Utiliser Fonction'                , 
	'LBL_RAW_TEXT'                 => 'Texte brut'                    , 
	'LBL_ENABLE_TO_CREATE_FILTERS' => 'Permettre de créer des filtres'    , 
	'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'Ce flux de travail a été créé avec une version précédente de vtiger. Les conditions ne peuvent être éditées. Vous pouvez choisir de recréer les conditions ou de conserver les anciannes (sans pouvoir les modifier).', 
	'LBL_USE_EXISTING_CONDITIONS'  => 'Conserver les conditions existantes'     , 
	'LBL_RECREATE_CONDITIONS'      => 'Recréer les conditions'         , 
	'LBL_SAVE_AND_CONTINUE'        => 'Enregistrer et suivant'             , 
	'LBL_ACTIVE'                   => 'Actif'                      , 
	'LBL_TASK_TYPE'                => 'Type de tâche'                   , 
	'LBL_TASK_TITLE'               => 'Titre de la tâche'                  , 
	'LBL_ADD_TASKS_FOR_WORKFLOW'   => 'Ajouter tâche au flux de travail'       , 
	'LBL_EXECUTE_TASK'             => 'Executer la tâche'                , 
	'LBL_SELECT_OPTIONS'           => 'Choisir les options'              , 
	'LBL_ADD_FIELD'                => 'Ajouter champ'                   , 
	'LBL_ADD_TIME'                 => 'Ajouter Heure'                    , 
	'LBL_TITLE'                    => 'Titre'                       , 
	'LBL_PRIORITY'                 => 'Priorité'                    , 
	'LBL_ASSIGNED_TO'              => 'Assigné à'                 , 
	'LBL_TIME'                     => 'Heure'                        , 
	'LBL_DUE_DATE'                 => 'Date d\'échéance'                    , 
	'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'La même valeur sera utilisée pour la date de début', 
	'LBL_EVENT_NAME'               => 'Nom de l\'activité'                  , 
	'LBL_TYPE'                     => 'Type'                        , 
	'LBL_METHOD_NAME'              => 'Nom de la méthode'                 , 
	'LBL_RECEPIENTS'               => 'Destinataires'                  , 
	'LBL_ADD_FIELDS'               => 'Ajouter champ'                  , 
	'LBL_SMS_TEXT'                 => 'Message SMS'                    , 
	'LBL_SET_FIELD_VALUES'         => 'Définir les valeurs du champ'            , 
	'LBL_IN_ACTIVE'                => 'Inactif'                   , 
	'LBL_SEND_NOTIFICATION'        => 'Envoyer Notification'           , 
	'LBL_START_TIME'               => 'Heure de début'                  , 
	'LBL_START_DATE'               => 'Date de début'                  , 
	'LBL_END_TIME'                 => 'Heure de fin'                    , 
	'LBL_END_DATE'                 => 'Date de fin'                    , 
	'LBL_ENABLE_REPEAT'            => 'Activer la récurrence'               , 
	'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'Aucune méthode disponible pour ce module', 
	'LBL_FINISH'                   => 'Terminer'                      , 
	'LBL_NO_TASKS_ADDED'           => 'Aucune tâche'                     , 
	'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'Impossible de supprimer un worflow par défaut', 
	'LBL_MODULES_TO_CREATE_RECORD' => 'Modules pour créer un enregistrement'    , 
	'LBL_EXAMPLE_EXPRESSION'       => 'Expression'                  , 
	'LBL_EXAMPLE_RAWTEXT'          => 'Texte brut'                     , 
	'LBL_VTIGER'                   => 'Vtiger'                      , 
	'LBL_EXAMPLE_FIELD_NAME'       => 'champ'                       , 
	'LBL_NOTIFY_OWNER'             => 'Notifier le propriétaire'                , 
	'LBL_ANNUAL_REVENUE'           => 'revenu annuel'              , 
	'LBL_EXPRESSION_EXAMPLE2'      => 'if mailingcountry == \'India\' then concat(firstname,\' \',lastname) else concat(lastname,\' \',firstname) end', 
	'Optional' => 'Optionnel',
	// traduction manquante
	'Summary' => 'Résumé',
	'Execution Condition' => 'Condition d\'éxecution',
	'is'                   => 'est'                      , 
	'equal'                   => 'égal'                      , 
	'does not equal'             => 'différent de'                , 
	'starts with'              => 'commence par'                 , 
	'ends with'                => 'finit par'                    , 
	'contains'                 => 'contient'                    , 
	'does not contains'         => 'ne contient pas'           , 
	'less than'                => 'inférieur à'               , 
	'greater than'             => 'supérieur à'               , 
	'less than or equal to'       => 'inférieur ou égal'         , 
	'greater than or equal to'         => 'supérieur ou égal'         , 
	'before'                   => 'avant'                      , 
	'after'                    => 'après'                       , 
	'between'                  => 'entre'                     , 
	'has changed'                  => 'est modifié'        , 
	'is empty'                  => 'est vide'        , 
	'is not empty'                  => 'est renseigné'        , 
    
	'Send Mail' => 'Envoyer Email',
	'Invoke Custom Function'                    => 'Utiliser une fonction personnalisée'    ,
	'Create Todo'                    => 'Créer tâche'                       ,
	'Create Event'                    => 'Créer activité'                       ,
	'Update Fields'                    => 'Mettre à jour des champs'        ,
	'Create Entity'                    => 'Créer une entité'      ,
	'SMS Task'                    => 'Envoyer SMS'                       ,
    
	'SCHEDULE_WORKFLOW' => 'Flux de travail programmé',
    'ON_SCHEDULE'=>'Programmé',    
    'LBL_RUN_WORKFLOW' =>'Fréquence programmée',
    'LBL_AT_TIME' => 'Heure d\'envoi',
    'LBL_SELECT_RECIEPIENTS' => 'Destinataires',
    'LBL_SPECIFIC_EMAIL_ADDRESS' => 'Email(s) supplémentaire(s)',
    'LBL_HOURLY' => 'Toutes les heures',
    'LBL_DAILY' => 'Quotidien',
    'LBL_WEEKLY' => 'Hebdomadaire',
    'LBL_SPECIFIC_DATE' => 'A une date donnée',
    'LBL_MONTHLY_BY_DATE' => 'Mensuel',
    'LBL_YEARLY' => 'Annuel',
    'LBL_ON_THESE_DAYS' => 'Jour(s) de la semaine',
    'LBL_SELECT_MONTH_AND_DAY' => 'Choisir le jour et le mois',
    'LBL_CHOOSE_DATE' => 'Choisir la date',    
    'LBL_SELECTED_DATES' => 'Dates Sélectionnées',
	'LBL_EDITING_WORKFLOW' => 'Édition du flux de travail',
	'Calendar'	 => 	'Calendrier' ,
	'LBL_MONTHLY_BY_WEEKDAY'	 => 	'Mensuel par jour de la semaine' ,
	'LBL_EXCEEDING_MAXIMUM_LIMIT'	 => 	'Limite maximale dépassée' ,
	'LBL_NEXT_TRIGGER_TIME'	 => 	'Prochaine exécution' ,
	'LBL_MESSAGE'	 => 	'Message' ,	
	'Workflows'	 => 	'Flux de travail' ,
	'Module'	 => 	'Module' ,
	
	// 7.1
	'LBL_ADD_RECORD' => 'Nouveau flux de travail',
	'LBL_FROM' => 'De',
	'ENTER_FROM_EMAIL_ADDRESS' => 'Entrez une adresse électronique pour l\'expéditeur',
	'LBL_ADD_TASK' => 'Ajouter action',
    'Portal Pdf Url' => 'Url du PDF du portail',
    'LBL_ADD_TEMPLATE' => 'Ajouter modèle',
    'LBL_LINEITEM_BLOCK_GROUP' => 'Bloc d\'éléments de ligne pour la taxe de groupe',
    'LBL_LINEITEM_BLOCK_INDIVIDUAL' => 'Bloc d\'éléments de ligne pour la taxe individuelle',
    'LBL_ADD_PDF' => 'Ajouter PDF',
	'Mobile Push Notification' => 'Notification push mobile',
    'LBL_WORKFLOW_NAME' => 'Nom du flux de travail',
    'LBL_TARGET_MODULE' => 'Module cible',
    'LBL_WORKFLOW_TRIGGER' => 'Déclencheur du flux de travail',
    'LBL_TRIGGER_WORKFLOW_ON' => 'Déclencher le flux de travail sur',
    'LBL_RECORD_CREATION' => 'Création d\'enregistrement',
    'LBL_RECORD_UPDATE' => 'Mise à jour d\'enregistrement',
    'LBL_TIME_INTERVAL' => 'Intervalle de temps',
    'LBL_RECURRENCE' => 'Récurrence',
    'LBL_FIRST_TIME_CONDITION_MET' => 'Seulement la première fois que les conditions sont remplies',
    'LBL_EVERY_TIME_CONDITION_MET' => 'A chaque fois que les conditions sont remplies',
    'LBL_WORKFLOW_CONDITION' => 'Condition du flux de travail',
    'LBL_WORKFLOW_ACTIONS' => 'Actions du flux de travail',
    'LBL_DELAY_ACTION' => 'Retarder l\'action',
    'LBL_FREQUENCY' => 'Fréquence',
    'LBL_SELECT_FIELDS' => 'Sélectionner les champs',
    'LBL_INCLUDES_CREATION' => 'Comprend la création',
    'LBL_ACTION_FOR_WORKFLOW' => 'Action pour le flux de travail',
    'LBL_WORKFLOW_SEARCH' => 'Recherche par nom',
	'LBL_ACTION_TYPE' => 'Type d\'action (Décompte actif)',
	'LBL_VTEmailTask' => 'Email',
    'LBL_VTEntityMethodTask' => 'Fonction personnalisée',
    'LBL_VTCreateTodoTask' => 'Tâche',
    'LBL_VTCreateEventTask' => 'Activité',
    'LBL_VTUpdateFieldsTask' => 'Mise à jour du champ',
    'LBL_VTSMSTask' => 'SMS', 
    'LBL_VTPushNotificationTask' => 'Notification mobile',
    'LBL_VTCreateEntityTask' => 'Créer enregistrement',
	'LBL_MAX_SCHEDULED_WORKFLOWS_EXCEEDED' => "Le nombre maximal (%s) de flux de travail planifiés a été dépassé",
);
$jsLanguageStrings = array(
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Statut enregistré' , 
	'JS_TASK_DELETED_SUCCESSFULLY' => 'Tâche supprimée'   , 
	'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'Les mêmes champs sont sélectionnés plusieurs fois', 
	'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'Flux de travail enregistré' , 
	
	// 7.1
    'JS_CHECK_START_AND_END_DATE'=>'La date et l\'heure de fin doivent être supérieures ou égales à la date et à l\'heure de début',
    'JS_TASK_STATUS_CHANGED' => 'Le statut des tâches a changé avec succès.',
    'JS_WORKFLOWS_STATUS_CHANGED' => 'Le statut du flux de travail a changé avec succès.',
    'VTEmailTask' => 'Envoyer email',
    'VTEntityMethodTask' => 'Appeler une fonction personnalisée',
    'VTCreateTodoTask' => 'Créer tâche',
    'VTCreateEventTask' => 'Créer activité',
    'VTUpdateFieldsTask' => 'Mettre les champs à jour',
    'VTSMSTask' => 'Tâche SMS', 
    'VTPushNotificationTask' => 'Notification push mobile',
    'VTCreateEntityTask' => 'Créer enregistrement',
    'LBL_EXPRESSION_INVALID' => 'Expression invalide',
);
