<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'SINGLE_Documents'             => 'Document'                    , 
	'Documents'                    => 'Documents'                   , 
	'LBL_ADD_RECORD'               => 'Ajouter document'                , 
	'LBL_RECORDS_LIST'             => 'Liste des documents '              , 
	'LBL_NOTE_INFORMATION'         => 'Information document'        , 
	'LBL_FILE_INFORMATION'         => 'Information fichier'         , 
	'LBL_DESCRIPTION'              => 'Description'                 , 
	'Title'                        => 'Titre'                       , 
	'File Name'                    => 'Nom du fichier'              , 
	'Note'                         => 'Notes'                       , 
	'File Type'                    => 'Type du fichier'             , 
	'File Size'                    => 'Taille'                      , 
	'Download Type'                => 'Type de téléchargement'    , 
	'Version'                      => 'Version'                     , 
	'Active'                       => 'Actif'                       , 
	'Download Count'               => 'Compteur de téléchargement', 
	'Folder Name'                  => 'Dossier'                 , 
	'Document No'                  => 'Document N°'                , 
	'Last Modified By'             => 'Modifié par'            , 
	'LBL_FOLDER_HAS_DOCUMENTS'     => 'Veuillez déplacer les fichiers du dossier avant suppression', 
	'LBL_DOWNLOAD_FILE'            => 'Télécharger le fichier'    , 
	'LBL_CHECK_FILE_INTEGRITY'     => 'Contrôler l\'intégrité du fichier', 
	'LBL_INTERNAL'                 => 'Interne'                     , 
	'LBL_EXTERNAL'                 => 'Externe'                     , 
	'LBL_MAX_UPLOAD_SIZE'          => 'Taille max. du fichier'         , 
	'LBL_MOVE'                     => 'Déplacer'                   , 
	'LBL_ADD_FOLDER'               => 'Ajouter dossier'          , 
	'LBL_FOLDERS_LIST'             => 'Liste des dossiers'                , 
	'LBL_FOLDERS'                  => 'Dossiers'                     , 
	'LBL_DOCUMENTS_MOVED_SUCCESSFULLY' => 'Documents déplacés!', 
	'LBL_DENIED_DOCUMENTS'         => 'Documents inacessibles selon vos droits'            , 
	'MB'                           => 'Mo'                          , 
	'LBL_ADD_NEW_FOLDER'           => 'Ajouter dossier'          , 
	'LBL_FOLDER_NAME'              => 'Répertoire'                 , 
	'LBL_FOLDER_DESCRIPTION'       => 'Description du dossier'          , 
	'LBL_FILE_AVAILABLE'           => 'Fichier disponible au téléchargement', 
	'LBL_FILE_NOT_AVAILABLE'       => 'Fichier non disponible au téléchargement', 
	'LBL_EMAIL_FILE_AS_ATTACHMENT'	 => 	'Envoyer le fichier par email' ,
	
	// 7.1
	'LBL_VIEW_FILE' => 'Voir le fichier',
	'LBL_PREVIEW_NOT_AVAILABLE' => 'Aperçu non disponible',
	'LBL_INTERNAL_DOCUMENT_TYPE' => 'Document interne',
	'LBL_EXTERNAL_DOCUMENT_TYPE' => 'Lien externe',
	'LBL_WEBDOCUMENT_TYPE' => 'Document web',
	'LBL_DRAG_&_DROP_FILE_HERE' => 'Glisser & déposer les fichiers ici',
	'LBL_WEB' => 'Web',
	'LBL_UPLOAD_DOCUMENT_TO_VTIGER' => 'Envoyer des documents vers vTiger',
	'LBL_UPLOAD_TO_DRIVE' => 'Envoyer vers Google Drive',
	'LBL_SELECT_FROM_DRIVE' => 'Sélectionner depuis Google Drive',
	'LBL_GOOGLE_DRIVE_FOLDERS' => 'Dossiers Google Drive',
	'LBL_ROOT' => 'Racine',
	'LBL_AUTHORIZE' => 'Autoriser',
	'LBL_DOCUMENT_SOURCE' => 'Source du document',
	'LBL_REVOKE_ACCESS_TO_DRIVE' => 'Révoquer l\'accès à Google Drive',
	'LBL_FILE_URL' => 'Lien du fichier',
	'LBL_UPLOAD_TO' => 'Envoyer vers',
	'LBL_NEW_DOCUMENT' => 'Nouveau document',
	'LBL_VTIGER' => 'vTiger',
	'LBL_CREATE_YOUR_OWN' => 'Créer votre propre',
	'LBL_SHARE_DOCUMENT' => 'Partager un document',
	'LBL_UPLOAD_TO_VTIGER' => 'Envoyer un document vers vTiger',
	'LBL_UPLOAD' => 'Envoyer',
	'LBL_SELECT_FILE_FROM_COMPUTER' => 'Sélectionner un fichier sur mon ordinateur',
	'LBL_FILE_UPLOAD' => 'Envoi de fichiers',
	'LBL_LINK_EXTERNAL_DOCUMENT' => 'Lien un document externe',
	'LBL_TO_SERVICE' => 'Vers %s',
	'LBL_FROM_SERVICE' => 'De %s',
	'LBL_CREATE_NEW' => 'Créer un nouveau %s',
	'LBL_SELECT_A_FOLDER_TO_MOVE' => 'Veuillez sélectionner un dossier à déplacer',
);
$jsLanguageStrings = array(
	'JS_EXCEEDS_MAX_UPLOAD_SIZE'   => 'Taille max. du fichier attainte', 
	'JS_NEW_FOLDER'                => 'Ajouter Dossier'                  , 
	'JS_MOVE_DOCUMENTS'            => 'Déplacer Documents'              , 
	'JS_ARE_YOU_SURE_YOU_WANT_TO_MOVE_DOCUMENTS_TO' => 'Confirmer le déplacement des fichiers vers ', 
	'JS_FOLDER'                    => 'Dossier'                      , 
	'JS_OPERATION_DENIED'          => 'Opération non autorisée'            , 
	'JS_FOLDER_IS_NOT_EMPTY'	   => 'Veuillez déplacer/supprimez tous les documents dans le dossier actuel avant de le supprimer' ,
	'JS_NOT_ALLOWED'	 => 	'ne sont pas autorisés' ,
	'JS_SPECIAL_CHARACTERS'	 => 	'Caractères spéciaux comme' ,
	
	// 7.1
	'JS_DELETE_AND_TRASH_FILE_IN_DRIVE' => 'Supprimer le fichier et le mettre dans la corbeille sur Google Drive',
	'JS_FAILED_TO_UPLOAD_FILE' => 'Impossible d\'envoyer le fichier',
	'JS_ARE_YOU_SURE_TO_REVOKE_ACCESS' => 'Êtes-vous sûr de vouloir révoquer l\'accès ?',
	'JS_ACCESS_REVOKED' => 'Accès révoqué',
	'JS_DELETE_AND_TRASH_FILE_IN_DROPBOX' => 'Supprimer le fichier et le mettre dans la corbeille sur Dropbox',
	'JS_UPLOAD_SUCCESSFUL' => 'Fichier envoyé',
	'JS_UPLOAD_FAILED' => 'L\'envoi du fichier a échoué',
	'JS_DOCUMENT_CREATED' => 'Document créé',
	'JS_DOCUMENT_CREATION_FAILED' => 'La création du document a échoué',
);